pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge
        
  - name: Automatic merge if dependency bump
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - check-success=Sider
      - check-success=Vercel
    actions:
      merge:
        method: merge
